const products = [
  {
    id: 0,
    title: 'Wingspan',
    price: 29.95,
    category: 'Familie',
    publisher: '999 Games',
    language: 'Nederlands',
    players: '1 tot 5',
    playtime: '60',
    age: '10',
    desc: 'Wingspan is een vogelspel vol tactiek en spanning. Als vogelliefhebber probeer je de beste leefomstandigheden voor de vogels in je opvangcentrum te creëren. Elke vogel breidt in één van zijn leefgebieden een ketting van krachtige combinaties uit. Deze leefgebieden richten zich op verschillende groeifactoren: voedsel pakken, eieren leggen en nieuwe vogelkaarten trekken. Wie bouwt het beste actiemotortje en scoort aan het einde van het spel de meeste punten met zijn vogels? \nElke beurt speel je een vogel, waarna je alle acties die zich in het betreffende leefgebied bevinden, mag uitvoeren. Zo kun je voedsel uit een “echt” vogelhuisje pakken, ei-miniaturen in nesten leggen of nieuwe vogels verzamelen. Alle opties leveren op verschillende manieren punten op. Het spel bevat 170 unieke vogelkaarten, die in combinatie met de verschillende bonuskaarten en de interactie met de andere spelers voor oneindige variatie zorgen. Het spel is ook solitair te spelen! ',
    image:
      'https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__imagepage/img/uIjeoKgHMcRtzRSR4MoUYl3nXxs=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4458123.jpg',
    youtube: 'https://www.youtube.com/embed/_g188X5vJCo',
  },
  {
    id: 1,
    title: 'Frostpunk',
    price: 19.95,
    category: 'Strategie',
    publisher: 'Glass Canon',
    language: 'Engels',
    players: '1-4',
    playtime: '120-150',
    age: '16',
    desc: 'In Frostpunk: The Board Game, up to four players will take on the role of leaders of a small colony of survivors in a post-apocalyptic world that was hit by a severe ice age. Their duty is to effectively manage both its infrastructure and citizens. The core gameplay will be brutal, challenging, and complex, but easy to learn. The citizens won’t just be speechless pieces on the board. Society members will issue demands and react accordingly to the current mood, so every decision and action bears consequences.\nThe players will decide the fate of their people. Will you treat them like another resource? Are you going to be an inspiring builder, a fearless explorer, or a bright scientist? Is your rule going to be a sting of tyranny or an era of law and equality?\nThe game is based on a bestseller video game by 11bit studios, the creators of This War Of Mine. The original (digital) edition of Frostpunk is a highly successful strategy-survival-city-builder, a BAFTA-nominee that originally launched in 2018.',
    image:
      'https://cf.geekdo-images.com/USLqrf7LGR-W1oBmbVoN9w__imagepage/img/2_k-9Y5ReNfQtKYcmcsHN4i0pIU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5508492.jpg',
    youtube: 'https://www.youtube.com/embed/XKGqjFB7D6Y',
  },
  {
    id: 2,
    title: 'Bloodborne',
    price: 24.95,
    category: 'Strategie',
    publisher: 'CMON',
    language: 'Engels',
    players: '1-4',
    playtime: '45-75',
    age: '14',
    desc: 'Revered for its healing techniques, the town of Yharnam is rapidly degrading as a plague that turns people into beasts spreads uncontrollably. As a Hunter, it falls to you to quell this growing threat. You will have to fight through beasts, monsters, and townsfolk alike to survive the night and discover the source of this madness. \nIn the campaign-based action-adventure Bloodborne: The Board Game, players take on the role of Hunters, working together against the game to uncover the mysteries hidden within the city of Yharnam and beyond. Featuring unique Trick Weapons, each with various forms and powers, Hunters have to think quickly and adapt their tactics to overcome the multitude of foes that stand in their way. Learn their behavior, exploit their weaknesses, and strike them down! Featuring unique card-driven combat, luck has little place here — success or failure depends on your choices and how you approach each engagement! \nOf course, against such horrific foes, death is a common occurrence, but worry not as death is no end for a Hunter. Those who fall in combat awaken in the Hunter\'s Dream, ready to return fresh to the fight. Be warned, however, that upon awakening you might find previous foes and obstacles returned, Worse, time is not on your side as the Blood Moon rises ever higher into the sky, spreading its madness across Yharnam. You must press ever forward if you and your comrades hope to complete the Hunt before the city meets an unfortunate end. \nAs you set out onto the Hunt, always remember the old adage: \n"We are born of the blood, made men by the blood, undone by the blood. Our eyes are yet to open... Fear the old blood."',
    image:
      'https://cf.geekdo-images.com/clKFvn2bUUPbY62eSmc-ig__imagepage/img/dtZczndlVT0nOsFceQbM0yeAGVo=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4757839.png',
    youtube: 'https://www.youtube.com/embed/ZlFelry1e1w',
  },
  {
    id: 3,
    title: 'Dog Park',
    price: 19.95,
    category: 'Familie',
    publisher: 'CMON',
    language: 'Engels',
    players: '1-4',
    playtime: '45-75',
    age: '14',
    desc: 'Welcome to Dog Park, a mid-weight, competitive set-collection and point-to-point movement game in which players take on the role of dog walkers who recruit, walk, and care for their dogs over four rounds. Each round is split into four phases: Recruitment Phase: Players compete in two rounds of offers to add dogs to their kennels. Offers are made with players reputation (victory points), so must be placed wisely. Selection Phase: Players decide which dogs to place on their lead to walk this round.\nWalking Phase: Players journey through the dog park with their fellow walkers, collecting resources, earning reputation, and interacting with other walkers. Home Time Phase: Players earn reputation for their walked dogs, and lose reputation for any unwalked dogs in their kennel. Players must choose their routes and dogs carefully to earn the best reputation and prove they are the most accomplished walker of them all. At the end of the game, the player with the most reputation wins.',
    image:
      'https://cf.geekdo-images.com/cCAAceyvbbqMXqX5QgwSmQ__imagepage/img/ytfqiJWea9uG8EHZ7ryDllrjhus=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6257426.jpg',
    youtube: 'https://www.youtube.com/embed/Ftq4t6aryo0',
  },
  {
    id: 4,
    title: 'Kingdom Come',
    price: 26.95,
    category: 'Familie',
    publisher: 'CMON',
    language: 'Engels',
    players: '1-4',
    playtime: '45-75',
    age: '14',
    desc: 'Enter the Lands of the Bohemian Crown at the onset of the Hussite wars. In times like these, trust is scarce, and faith is shaken. It is a conflict of religious beliefs that turns brother against brother, and it is the common man who pays the toll. Whether you hide in the deepest cellar or the tallest tower of a monastery, the flames of war will reach you there too. Tread lightly -- and godspeed!Kingdom Come: Deliverance - The Board Game is a 1-4 player cooperative campaign app-driven board game that brings the Lands of the Bohemian Crown to your table! Live through the harrowing times and immerse yourself in this epic narrative journey in the Holy Roman Empire.',
    image:
      'https://cf.geekdo-images.com/RwZfncmOpD-UyfI-GOUjoA__imagepage/img/98qy3lkOMrFvvxld-VpS0l00Mms=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7063621.jpg',
    youtube: 'https://www.youtube.com/embed/ce-xLzn_oe4',
  },
  {
    id: 5,
    title: 'Elysium',
    price: 16.95,
    category: 'Strategie',
    publisher: 'CMON',
    language: 'Engels',
    players: '1-4',
    playtime: '45-75',
    age: '14',
    desc: 'Mythic Greece. As an upstart demigod, you want to earn the favor of the Olympians and become a figure of legend yourself. Gather heroes and powerful artifacts, please the gods and bear their power to write your own epic tale. Let your allies achieve their destiny and enter the Elysium, home of the glorious and the brave. Once the stories are written, only one demigod will be chosen to stand at the side of Zeus. \nElysium is a game of set collecting and combinations in which players recruit cards representing heroes, items, powers and gods. These cards have many different powers and you can create powerful combination to earn gold (the help of the gods) and victory points (the favor of the gods). Each card belongs to one of the eight Olympians gods (a family), and shows a level (1 to 3).',
    image:
      'https://cf.geekdo-images.com/hNyO7u1pR3oSxKTELS7n2w__imagepage/img/ZTdESZYeAjRFjUecbH5bXu1Wp1M=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2837103.png',
    youtube: 'https://www.youtube.com/embed/jPac0pmLbak',
  },
  {
    id: 6,
    title: 'The Thing',
    price: 23.95,
    category: 'Familie',
    publisher: 'CMON',
    language: 'Engels',
    players: '1-4',
    playtime: '45-75',
    age: '14',
    desc: 'The Thing is a game that mixes different mechanisms to create an experience that is as faithful as possible to that of the original film. It is a "hidden role" game, in which one player is initially the Thing and the others players are humans. The purpose of the Thing is to infect others, to prevent the survivors from escaping from the base (which can happen three different ways), or to try to escape with them by behaving as a human. In addition to these elements, players also have to manage Outpost 31. \nOn the map are the same rooms as seen in the film, and each of these rooms allows players to perform a different action. Human players have to feed themselves and keep the boiler and the generator on to avoid being in the cold and dark. The Thing will try to sabotage these places to make life difficult for humans...or not, trying to camouflage itself among the humans and infect them when the perfect opportunity presents itself.',
    image:
      'https://cf.geekdo-images.com/dJCtZr6_dFDIg4o8tMYqCA__imagepage/img/_uGOge0s9Nefkl3mfcZcHB7kLpE=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5089905.jpg',
    youtube: 'https://www.youtube.com/embed/CzwOCmk5gVQ',
  },
  {
    id: 7,
    title: 'Earth',
    price: 34.95,
    category: 'Party',
    publisher: 'CMON',
    language: 'Engels',
    players: '1-4',
    playtime: '45-75',
    age: '14',
    desc: 'Earth, the soil that supports and sustains our beautiful planet, Earth. Over thousands of years of evolution and adaptation the flora and fauna of this unique planet have grown and developed into amazing life forms, creating symbiotic ecosystems and habitats. It’s time to jump into these rich environments and create some amazing natural synergies that replicate and extrapolate on Earth’s amazing versatility and plethora of natural resources. Create a self-supporting engine of growth, expansion and supply where even your unused plants become compost for future growth. \nEarth is an open world engine builder for 1 to 5 players with simple rules but tons of strategic possibilities. With its encyclopedic nature and the enormous number of unique cards and combinations, every single game will allow you to discover new synergies and connections, just as our vast and fascinating world allows us to do!',
    image:
      'https://cf.geekdo-images.com/0xqF_KyOb7V26Lu5YT3fxw__imagepage/img/sxzhjfiLwG7mtEkRpAvsw1P5cec=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6699821.jpg',
    youtube: 'https://www.youtube.com/embed/Soli678OMOE',
  },
  {
    id: 8,
    title: 'Ticket to Ride',
    price: 14.95,
    category: 'Familie',
    publisher: 'Days of Wonder',
    language: 'Nederlands',
    players: '2-5',
    playtime: '60',
    age: '8',
    desc: "Als Europese treinmaatschappij leg je in Ticket to Ride trein verbindingen aan tussen verschillende steden. Sint Petersburg- Madird, Amsterdam- Berlin , je gaat heel Europa door en je verbind de routes die de meeste punten waard zijn. Let ook goed op je opdrachten kaarten want deze zijn veel punten waard en zorg er voor dat de andere spelers je niet te snel af zijn.Ticket to Ride is een kwalitatief hoogwaardig bordspel waar de hele familie heel veel lol aan zal beleven. Bovendien wordt de topografische kennis ook even flink bij gespijkerd. Als extraatje zit bij ieder spel een code die toegang geeft tot de Ticket to Ride site waar het spel online gespeeld kan worden.",
    image:
      'https://cf.geekdo-images.com/0K1AOciqlMVUWFPLTJSiww__imagepage/img/pC5hC440R46jn4EpfdYV5rL4VOc=/fit-in/900x600/filters:no_upscale():strip_icc()/pic66668.jpg',
    youtube: 'https://www.youtube.com/embed/Q0bWLcr-gX4',
  },
  {
    id: 9,
    title: 'Marvel Champions',
    price: 59.95,
    category: 'Party',
    publisher: 'Fantasy Flight Games',
    language: 'Engels',
    players: '1-4',
    playtime: '45-90',
    age: '12',
    desc: 'Marvel Champions: The Card Game is een coöperatieve Living Card Game waarin spelers in de huid kruipen van Marvel-helden die strijden om de plannen van gemene schurken te dwarsbomen. In het spel zullen spelers een beroep doen op iconische bondgenoten, krachtige wapens en bepantsering gebruiken en verwoestende tactieken ontketenen terwijl ze vechten om de schurken van het Marvel-universum te verslaan. \nIn elk scenario van Marvel Champions: The Card Game worden de helden geconfronteerd met een krachtige schurk met snode plannen, evenals hun eigen persoonlijke vijanden die in het heldendeck kunnen worden geschud. Bij elke beurt zullen spelers moeten beslissen of ze als een superheld willen spelen en de schurk direct willen bevechten, of in hun alter ego willen veranderen om schade te herstellen, hun troepen voor te bereiden en indirect tegen de schurk te vechten (wat een interessante strategische beslissing is tijdens elke beurt). Als de helden de slechterik kunnen verslaan voordat ze hun gemene plan hebben voltooid, winnen de helden het spel. ',
    image:
      'https://cf.geekdo-images.com/kRvUgYiaOq07kC67ZK5UoQ__imagepage/img/ifaw5M-Z2eEFir0ImkbNzxMbaOk=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4900321.jpg',
    youtube: 'https://www.youtube.com/embed/2HfaNyzAkvQ',
  },
  {
    id: 10,
    title: 'Codenames',
    price: 19.95,
    category: 'Party',
    publisher: 'White Goblin Games',
    language: 'Nederlands',
    players: '2-8',
    playtime: '20',
    age: '8',
    desc: 'De bazen van twee geheime diensten kennen de identiteit van 25 agenten, maar hun ondergeschikten kennen alleen de codenamen van de andere agenten. Wie kan het eerste contact maken met al zijn collega-spionnen?\nDe bazen geven hints aan hun ondergeschikten door een woord en een getal te noemen. Zo kunnen ze bijvoorbeeld Dier 2 zeggen als 2 van hun spionnen een codenaam hebben dat een dier voorstelt. Het team overlegt vervolgens en wijst één van de kaartjes met codenamen aan. De baas geeft vervolgens aan bij welk team deze kaart hoort, zodat de anderen weten of ze de hint juist of verkeerd geïnterpreteerd hebben.\nHet team dat als eerste al hun collega\'s weet te identificeren, wint dit spannende spel. Als een team echter per ongeluk de huurmoordenaar kiest, dan verliezen ze meteen.  ',
    image:
      'https://cf.geekdo-images.com/F_KDEu0GjdClml8N7c8Imw__imagepage/img/rc_Do8f5v41nWEGcwHE1eKAkIfI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2582929.jpg',
    youtube: 'https://www.youtube.com/embed/C97mCg9AxZc',
  },
  {
    id: 11,
    title: 'Captain Sonar',
    price: 44.95,
    category: 'Party',
    publisher: 'Asmodee',
    language: 'Engels',
    players: '2-8',
    playtime: '45',
    age: '14',
    desc: 'In een onderzeeboot is het essentieel dat je jouw positie niet verraadt met geluid, maar je zult toch goed moeten communiceren om de vijandelijke onderzeeër te torpederen voordat hij dat bij jou doet!\nIn dit spel worden de spelers over twee teams verdeeld die elkaars onderzeeër tot zinken willen brengen. Iedereen heeft een eigen taak, zoals het verplaatsen van de onderzeeër, de vijandelijke onderzeeër vinden door goed te luisteren naar het andere team, het laden van de torpedobuizen en jouw onderzeeër drijvende te houden.\nOmdat iedereen alleen zijn eigen stukje ziet, is een goede communicatie vereist. Alleen dan kan de kapitein namelijk op het juiste moment overgaan tot een aanval waarbij hopelijk de vijandelijke onderzeeër geraakt wordt.\nDit spel kan gespeeld worden in een ultra-spannende real-time modus, maar ook in een puzzel-achtige modus waarin er wel een beurtvolgorde gehanteerd wordt. Tevens zijn er diverse verschillende scenario\'s die zorgen voor verschillende moeilijkheidsgraden. ',
    image:
      'https://cf.geekdo-images.com/Dpu5nFJu4UUJ4Y50WyKueg__imagepagezoom/img/p23JzDsS2C5VZ1FYkAWVCVkhENU=/fit-in/1200x900/filters:no_upscale():strip_icc()/pic7069368.jpg',
    youtube: 'https://www.youtube.com/embed/Yjo4iXyDPtw',
  },
  {
    id: 12,
    title: 'Decrypto',
    price: 19.95,
    category: 'Party',
    publisher: 'Scorpion Masqué',
    language: 'Nederlands',
    players: '3-8',
    playtime: '30',
    age: '12',
    desc: 'Decrypto is een communicatiespel waarin je deel uitmaakt van een team van codekrakers.\nJouw missie: verzend geheime codes naar je teamgenoten zonder dat je tegenstanders ze onderscheppen.Ga daarom op zoek naar een manier van communiceren waarbij jouw teamgenoten jou begrijpen, maar zorg dat je communicatie goed gecodeerd is om je tegenstander te verwarren. Tegelijkertijd probeer je ook de codes van je tegenstanders te ontcijferen. Jouw team wint het spel zodra je 2 onderscheppingsfiches weet te bemachtigen. Je ontvangt 1 onderscheppingsfiche voor elke keer dat je de code van je tegenstanders weet te onderscheppen. Jouw team verliest het spel als je 2 miscommunicatie fiches hebt ontvangen. Je ontvangt 1 miscommunicatie fiche voor elke keer dat jouw team de code van je Encryptor niet weet te raden.',
    image:
      'https://cf.geekdo-images.com/hHZWXnUTMYDd_KTAM6Jwlw__imagepage/img/txjLrQy6eZNhk1caOxfTPn54mac=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3759421.jpg',
    youtube: 'https://www.youtube.com/embed/jcM3Y9KchMs',
  },
];

module.exports = products;
